# Generated by Django 2.2.3 on 2019-07-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(default=None, verbose_name='저자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='update_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
